#!/usr/bin/env bash
# setup-tools:cron 装出的 crontab 安装脚本（plugins/setup-tools/skills/cron/template/cron/）的测试。
#   bash tools/tests/cron/run.sh [-v] [<用例名>...]
# 环境变量 CRON_TEMPLATE_DIR 可指向另一份 cron 模板目录（如故意改坏的副本），默认测仓库里的那份。
#
# 绝不碰真实 crontab：被测脚本一律经 env -i 运行，PATH 只含自建的 bin 目录——里面是必需工具的软链，
# 外加一个读写 $FAKE_CRONTAB 文件的假 crontab；另一份 bin 不含 crontab，测「没有 crontab 命令」。
# 两份 bin 建好后先核对：前者的 crontab 是那个假脚本，后者没有 crontab，任一不符整套不跑。
#
# 每个用例在自己的目录里放项目：<项目根>/scripts/cron/ 下是模板的四个文件（即模板默认的深度），
# tasks.conf 界线行之后追加一个任务。

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)/lib/common.sh"

CRON_SRC=${CRON_TEMPLATE_DIR:-$REPO_ROOT/plugins/setup-tools/skills/cron/template/cron}
CRON_SRC=$(cd "$CRON_SRC" && pwd -P)
for f in common.sh install.sh uninstall.sh tasks.conf; do
  [ -f "$CRON_SRC/$f" ] || die "找不到 cron 模板文件：$CRON_SRC/$f"
done

SNAP_BEFORE=$(repo_snapshot)
make_tmp

# ---------------------------------------------------------------------------
# 自建 bin 与假 crontab

BIN_NOCRON=$T/cronbin-nocron
BIN_CRON=$T/cronbin
mkdir -p "$BIN_NOCRON" "$BIN_CRON"
for tool in sh awk sed tr cksum cut find head date wc basename dirname mkdir uname cat rm grep; do
  p=$(type -P "$tool") || die "找不到必需的工具：$tool"
  ln -s "$p" "$BIN_NOCRON/$tool"
  ln -s "$p" "$BIN_CRON/$tool"
done
cat >"$BIN_CRON/crontab" <<'EOF'
#!/bin/sh
# 假 crontab：内容存在 $FAKE_CRONTAB 文件里，只支持 install.sh / uninstall.sh 用到的 -l、-r、-。
f=${FAKE_CRONTAB:?FAKE_CRONTAB 未设置}
case "${1:-}" in
  -l) [ -f "$f" ] || { echo "crontab: no crontab for tester" >&2; exit 1; }; cat "$f" ;;
  -r) [ -f "$f" ] || { echo "crontab: no crontab for tester" >&2; exit 1; }; rm -f "$f" ;;
  -) cat >"$f" ;;
  *) echo "fake crontab: 不支持的参数 $*" >&2; exit 2 ;;
esac
EOF
chmod +x "$BIN_CRON/crontab"
# 安全核对：有 crontab 的那份解析到的是假脚本，另一份解析不到 crontab。
[ "$(env -i PATH="$BIN_CRON" "$BIN_CRON/sh" -c 'command -v crontab')" = "$BIN_CRON/crontab" ] \
  || die "安全检查失败：自建 bin 里的 crontab 不是假脚本"
[ ! -L "$BIN_CRON/crontab" ] || die "安全检查失败：假 crontab 不能是软链"
if env -i PATH="$BIN_NOCRON" "$BIN_NOCRON/sh" -c 'command -v crontab' >/dev/null 2>&1; then
  die "安全检查失败：不含 crontab 的 bin 里解析到了 crontab"
fi

# ---------------------------------------------------------------------------
# 夹具与小工具

# 每个用例自己的假 crontab 文件。
crontab_file() { echo "$CASE_DIR/crontab"; }

# 运行被测脚本：cron_sh [--nocron] [--env K=V]... <脚本路径> [参数]...
# 环境只有 PATH、HOME、LC_ALL（默认 C，可用 --env 覆盖）、FAKE_CRONTAB 与 --env 给的变量。
cron_sh() {
  local bin=$BIN_CRON envs=()
  while [ $# -gt 0 ]; do
    case $1 in
      --nocron) bin=$BIN_NOCRON ;;
      --env) envs+=("$2"); shift ;;
      *) break ;;
    esac
    shift
  done
  run_at "$CASE_DIR" env -i PATH="$bin" HOME="$HOME" LC_ALL=C FAKE_CRONTAB="$(crontab_file)" \
    ${envs[@]+"${envs[@]}"} "$bin/sh" "$@"
}

# 建项目：new_project <项目根> [<脚本目录，相对项目根，默认 scripts>]，脚本目录写入 CRON。
new_project() {
  local root=$1 sub=${2:-scripts}
  CRON=$root/$sub/cron
  mkdir -p "$CRON"
  cp "$CRON_SRC/"* "$CRON/"
  printf '%s\n' "测试任务 | */5 * * * * | echo hi" >>"$CRON/tasks.conf"
}

phys() { (cd "$1" && pwd -P); }

crontab_text() { cat "$(crontab_file)" 2>/dev/null || true; }

# crontab 里某个标记的区块个数。
block_count() { # block_count <标记>
  local n
  n=$(grep -cxF "# >>> CRON:$1 >>>" "$(crontab_file)" 2>/dev/null) || true
  echo "${n:-0}"
}

# 某个标记的区块第二行记着的项目根。
block_owner() { # block_owner <标记>
  awk -v s="# >>> CRON:$1 >>>" 'hit { sub(/^# /, ""); print; exit } $0 == s { hit = 1 }' "$(crontab_file)"
}

# 去掉区块里带时间戳的那一行，用于比较两次安装的结果。
without_timestamp() { grep -v '^# generated by install.sh at ' || true; }

OTHER_JOBS='MAILTO=""
0 0 * * * /usr/local/bin/other-job --daily
# 别的工具写的注释'

seed_crontab() { printf '%s\n' "$OTHER_JOBS" >"$(crontab_file)"; }

crontab_sum() { cksum <"$(crontab_file)" 2>/dev/null || echo none; }

# 从 dry-run 的首行取标记。
dry_run_tag() { # dry_run_tag [cron_sh 的选项]... <install.sh>
  local out
  out=$(cron_sh "$@" --dry-run) || return 1
  printf '%s\n' "$out" | head -n 1 | sed -n 's/^# >>> CRON:\(.*\) >>>$/\1/p'
}

# ---------------------------------------------------------------------------
# dry-run

register cron_dry_run_does_not_write
case_cron_dry_run_does_not_write() {
  new_project "$CASE_DIR/my-app"
  seed_crontab
  local before root
  before=$(crontab_sum)
  root=$(phys "$CASE_DIR/my-app")
  try cron_sh "$CRON/install.sh" --dry-run
  expect_rc 0 "dry-run"
  expect_out "# >>> CRON:MY_APP >>>"
  expect_out "# $root"
  expect_out "*/5 * * * * cd \"$root\" && { echo hi ; } >> \"$root/logs/cron/cron.log\" 2>&1"
  expect_out "# <<< CRON:MY_APP <<<"
  expect_eq "$(crontab_sum)" "$before" "dry-run 不写 crontab"
  [ ! -e "$root/logs" ] || fail "dry-run 不应建日志目录"
}

register cron_without_crontab_command
case_cron_without_crontab_command() {
  new_project "$CASE_DIR/my-app"
  try cron_sh --nocron "$CRON/install.sh" --dry-run
  expect_rc 0 "没有 crontab 命令时 dry-run"
  expect_out "# >>> CRON:MY_APP >>>"
  try cron_sh --nocron "$CRON/install.sh"
  expect_rc 1 "没有 crontab 命令时 install"
  expect_out "找不到 crontab 命令"
  try cron_sh --nocron "$CRON/uninstall.sh"
  expect_rc 1 "没有 crontab 命令时 uninstall"
  expect_out "找不到 crontab 命令"
  [ ! -e "$(crontab_file)" ] || fail "不应写出 crontab"
  [ ! -e "$CASE_DIR/my-app/logs" ] || fail "install 报错时不应建日志目录"
}

register cron_unknown_argument
case_cron_unknown_argument() {
  new_project "$CASE_DIR/my-app"
  try cron_sh "$CRON/install.sh" --force
  expect_rc 1 "未知参数"
  expect_out "未知参数: --force"
  [ ! -e "$(crontab_file)" ] || fail "不应写出 crontab"
}

register cron_missing_tasks_file
case_cron_missing_tasks_file() {
  new_project "$CASE_DIR/my-app"
  rm "$CRON/tasks.conf"
  try cron_sh "$CRON/install.sh"
  expect_rc 1 "tasks.conf 缺失"
  expect_out "找不到任务清单"
  [ ! -e "$(crontab_file)" ] || fail "不应写出 crontab"
}

# ---------------------------------------------------------------------------
# 安装、重装、卸载

register cron_install_into_empty_crontab
case_cron_install_into_empty_crontab() {
  new_project "$CASE_DIR/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "首次安装"
  expect_out "已安装定时任务（crontab 标记 MY_APP）"
  expect_eq "$(head -n 1 "$(crontab_file)")" "# >>> CRON:MY_APP >>>" "没有别的内容时区块就是全部，开头不留空行"
  expect_eq "$(tail -n 1 "$(crontab_file)")" "# <<< CRON:MY_APP <<<" "区块的最后一行"
  [ -d "$CASE_DIR/my-app/logs/cron" ] || fail "应建日志目录"
}

register cron_install_and_reinstall_idempotent
case_cron_install_and_reinstall_idempotent() {
  new_project "$CASE_DIR/my-app"
  seed_crontab
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "首次安装"
  expect_eq "$(block_count MY_APP)" 1 "首次安装后的区块数"
  local first
  first=$(crontab_text | without_timestamp)
  expect_eq "$(crontab_text | head -n 3)" "$OTHER_JOBS" "原有内容原样保留在前面"
  expect_eq "$(crontab_text | tail -n 1)" "# <<< CRON:MY_APP <<<" "区块追加在末尾"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "重装"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "再重装"
  expect_eq "$(block_count MY_APP)" 1 "重装后区块只有一份"
  expect_eq "$(crontab_text | without_timestamp)" "$first" "重装结果与首次安装一致（除时间戳）"
}

register cron_install_updates_tasks
case_cron_install_updates_tasks() {
  new_project "$CASE_DIR/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "首次安装"
  printf '%s\n' "第二个任务 | 0 3 * * * | echo second" >>"$CRON/tasks.conf"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "改清单后重装"
  expect_eq "$(block_count MY_APP)" 1 "区块只有一份"
  grep -qF '{ echo second ; }' "$(crontab_file)" || fail "新加的任务应装上"
  grep -qF '{ echo hi ; }' "$(crontab_file)" || fail "原有任务仍在"
}

register cron_uninstall_keeps_other_content
case_cron_uninstall_keeps_other_content() {
  new_project "$CASE_DIR/my-app"
  seed_crontab
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "安装"
  try cron_sh "$CRON/uninstall.sh"
  expect_rc 0 "卸载"
  expect_out "已移除本项目的定时任务（crontab 标记 MY_APP）"
  expect_eq "$(crontab_text)" "$OTHER_JOBS" "卸载后只剩原有内容"
  try cron_sh "$CRON/uninstall.sh"
  expect_rc 0 "再卸载"
  expect_out "无需卸载"
  expect_eq "$(crontab_text)" "$OTHER_JOBS" "没有区块时不动 crontab"
}

register cron_uninstall_only_block_removes_crontab
case_cron_uninstall_only_block_removes_crontab() {
  new_project "$CASE_DIR/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "安装"
  try cron_sh "$CRON/uninstall.sh"
  expect_rc 0 "卸载"
  [ ! -e "$(crontab_file)" ] || fail "crontab 只剩空白时应整份删除（crontab -r）"
  try cron_sh "$CRON/uninstall.sh"
  expect_rc 0 "没有 crontab 时卸载"
  expect_out "无需卸载"
}

register cron_two_projects_coexist
case_cron_two_projects_coexist() {
  new_project "$CASE_DIR/alpha"
  local a=$CRON
  new_project "$CASE_DIR/beta"
  local b=$CRON
  seed_crontab
  try cron_sh "$a/install.sh"
  expect_rc 0 "装 alpha"
  try cron_sh "$b/install.sh"
  expect_rc 0 "装 beta"
  expect_eq "$(block_count ALPHA)/$(block_count BETA)" 1/1 "两个区块各一份"
  local beta_block
  beta_block=$(awk '$0 == "# >>> CRON:BETA >>>" { p = 1 } p { print } $0 == "# <<< CRON:BETA <<<" { p = 0 }' "$(crontab_file)")
  try cron_sh "$a/install.sh"
  expect_rc 0 "重装 alpha"
  try cron_sh "$a/uninstall.sh"
  expect_rc 0 "卸载 alpha"
  expect_eq "$(block_count ALPHA)" 0 "alpha 的区块已删"
  expect_eq "$(awk '$0 == "# >>> CRON:BETA >>>" { p = 1 } p { print } $0 == "# <<< CRON:BETA <<<" { p = 0 }' "$(crontab_file)")" \
    "$beta_block" "beta 的区块原样保留"
  expect_eq "$(crontab_text | head -n 3)" "$OTHER_JOBS" "原有内容保留"
}

# ---------------------------------------------------------------------------
# 标记撞车与接管

# 撞车时 install、uninstall、dry-run 都报错退出 1，对方的区块不变。
expect_collision() { # expect_collision <install.sh 所在目录> <标记> <对方项目根>
  local dir=$1 tag=$2 owner=$3 before cmd
  before=$(crontab_sum)
  for cmd in "install.sh" "install.sh --dry-run" "uninstall.sh"; do
    # shellcheck disable=SC2086
    try cron_sh "$dir/"$cmd
    expect_rc 1 "撞车时 $cmd"
    expect_out "标记 $tag 已被 $owner 使用" "撞车时 $cmd"
    expect_eq "$(crontab_sum)" "$before" "撞车时 $cmd 不动 crontab"
  done
  expect_eq "$(block_count "$tag")" 1 "对方的区块仍是一份"
  expect_eq "$(block_owner "$tag")" "$owner" "区块仍记着对方的项目根"
}

register cron_collision_same_name_other_path
case_cron_collision_same_name_other_path() {
  new_project "$CASE_DIR/p1/my-app"
  local a=$CRON
  new_project "$CASE_DIR/p2/my-app"
  local b=$CRON
  seed_crontab
  try cron_sh "$a/install.sh"
  expect_rc 0 "装 p1/my-app"
  expect_collision "$b" MY_APP "$(phys "$CASE_DIR/p1/my-app")"
}

register cron_collision_normalized_name
case_cron_collision_normalized_name() {
  new_project "$CASE_DIR/my-app"
  local a=$CRON
  new_project "$CASE_DIR/my_app"
  local b=$CRON
  try cron_sh "$a/install.sh"
  expect_rc 0 "装 my-app"
  expect_collision "$b" MY_APP "$(phys "$CASE_DIR/my-app")"
  # 反过来：my_app 先装，my-app 同样撞车
  try cron_sh "$a/uninstall.sh"
  expect_rc 0 "卸载 my-app"
  try cron_sh "$b/install.sh"
  expect_rc 0 "装 my_app"
  expect_collision "$a" MY_APP "$(phys "$CASE_DIR/my_app")"
}

register cron_collision_fixed_tag_resolves
case_cron_collision_fixed_tag_resolves() {
  new_project "$CASE_DIR/p1/my-app"
  local a=$CRON
  new_project "$CASE_DIR/p2/my-app"
  local b=$CRON
  try cron_sh "$a/install.sh"
  expect_rc 0 "装 p1/my-app"
  # 按 common.sh 的说明改成固定标记后不再撞车
  sed 's/^CRON_TAG=\${CRON_TAG:-\$(default_tag)}$/CRON_TAG=${CRON_TAG:-MY_APP_TWO}/' "$b/common.sh" >"$b/common.sh.new"
  mv "$b/common.sh.new" "$b/common.sh"
  grep -q 'MY_APP_TWO' "$b/common.sh" || fail "没改到 common.sh 的 CRON_TAG 默认值"
  try cron_sh "$b/install.sh"
  expect_rc 0 "改成固定标记后安装"
  expect_eq "$(block_count MY_APP)/$(block_count MY_APP_TWO)" 1/1 "两个区块各一份"
}

register cron_moved_project_takes_over
case_cron_moved_project_takes_over() {
  new_project "$CASE_DIR/old/my-app"
  seed_crontab
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "在旧位置安装"
  mkdir -p "$CASE_DIR/new"
  mv "$CASE_DIR/old/my-app" "$CASE_DIR/new/my-app"
  try cron_sh "$CASE_DIR/new/my-app/scripts/cron/install.sh"
  expect_rc 0 "搬走后在新位置安装"
  expect_eq "$(block_count MY_APP)" 1 "只剩一个区块"
  expect_eq "$(block_owner MY_APP)" "$(phys "$CASE_DIR/new/my-app")" "区块记着新位置"
  expect_eq "$(crontab_text | head -n 3)" "$OTHER_JOBS" "原有内容保留"
}

register cron_old_dir_without_scripts_taken_over
case_cron_old_dir_without_scripts_taken_over() {
  new_project "$CASE_DIR/old/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "在旧位置安装"
  mkdir -p "$CASE_DIR/new"
  cp -R "$CASE_DIR/old/my-app" "$CASE_DIR/new/my-app"
  # 旧目录还在，但已没有 cron/common.sh：当作搬走了
  rm -rf "$CASE_DIR/old/my-app/scripts"
  try cron_sh "$CASE_DIR/new/my-app/scripts/cron/install.sh"
  expect_rc 0 "旧目录已没有脚本时接管"
  expect_eq "$(block_count MY_APP)" 1 "只剩一个区块"
  expect_eq "$(block_owner MY_APP)" "$(phys "$CASE_DIR/new/my-app")" "区块记着新位置"
}

register cron_owner_scan_skips_node_modules
case_cron_owner_scan_skips_node_modules() {
  new_project "$CASE_DIR/old/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "在旧位置安装"
  # 旧项目只剩 node_modules 里的一份 cron/common.sh（依赖包带的），不算仍在用
  mkdir -p "$CASE_DIR/old/my-app/node_modules/pkg/cron"
  mv "$CASE_DIR/old/my-app/scripts/cron/common.sh" "$CASE_DIR/old/my-app/node_modules/pkg/cron/"
  rm -rf "$CASE_DIR/old/my-app/scripts"
  new_project "$CASE_DIR/new/my-app"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "node_modules 里的 common.sh 不算"
  expect_eq "$(block_owner MY_APP)" "$(phys "$CASE_DIR/new/my-app")" "区块由新位置接管"
}

register cron_deep_project_not_mistaken_as_moved
case_cron_deep_project_not_mistaken_as_moved() {
  # 脚本放在项目根下第 6 层：按 common.sh 的说明把 PROJECT_ROOT 默认值的上溯层级改深
  new_project "$CASE_DIR/deep/my-app" "l1/l2/l3/l4/l5"
  local a=$CRON
  sed 's#\$SCRIPT_DIR/\.\./\.\.#$SCRIPT_DIR/../../../../../..#' "$a/common.sh" >"$a/common.sh.new"
  mv "$a/common.sh.new" "$a/common.sh"
  grep -qF '$SCRIPT_DIR/../../../../../..' "$a/common.sh" || fail "没改到 PROJECT_ROOT 的上溯层级"
  try cron_sh "$a/install.sh"
  expect_rc 0 "装深层项目"
  expect_eq "$(block_owner MY_APP)" "$(phys "$CASE_DIR/deep/my-app")" "深层项目的项目根"
  new_project "$CASE_DIR/other/my-app"
  expect_collision "$CRON" MY_APP "$(phys "$CASE_DIR/deep/my-app")"
}

# ---------------------------------------------------------------------------
# 标记的计算

register cron_tag_ascii_names
case_cron_tag_ascii_names() {
  local pair name want got
  for pair in "my-app=MY_APP" "My.App2=MY_APP2" "a b=A_B" "x_9=X_9"; do
    name=${pair%%=*}
    want=${pair#*=}
    new_project "$CASE_DIR/$name"
    got=$(dry_run_tag "$CRON/install.sh")
    expect_eq "$got" "$want" "目录名 $name 的标记"
  done
}

register cron_tag_non_ascii_locale_independent
case_cron_tag_non_ascii_locale_independent() {
  local name root want c utf8 zh
  for name in "项目" "项目2" "my项目" "---" "café"; do
    new_project "$CASE_DIR/$name"
    root=$(phys "$CASE_DIR/$name")
    want=P$(printf '%s' "$root" | cksum | cut -d' ' -f1)
    c=$(dry_run_tag "$CRON/install.sh")
    utf8=$(dry_run_tag --env LC_ALL=en_US.UTF-8 "$CRON/install.sh")
    zh=$(dry_run_tag --env LC_ALL=zh_CN.UTF-8 "$CRON/install.sh")
    expect_eq "$c" "$want" "目录名 $name 在 C locale 下的标记"
    expect_eq "$utf8" "$want" "目录名 $name 在 en_US.UTF-8 下的标记"
    expect_eq "$zh" "$want" "目录名 $name 在 zh_CN.UTF-8 下的标记"
  done
  # 按一种 locale 装、另一种 locale 重装与卸载，仍是同一个区块
  new_project "$CASE_DIR/中文项目"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "C locale 安装"
  try cron_sh --env LC_ALL=en_US.UTF-8 "$CRON/install.sh"
  expect_rc 0 "UTF-8 locale 重装"
  expect_eq "$(grep -c '^# >>> CRON:' "$(crontab_file)")" 1 "两种 locale 下是同一个区块"
  try cron_sh --env LC_ALL=zh_CN.UTF-8 "$CRON/uninstall.sh"
  expect_rc 0 "另一种 locale 卸载"
  [ ! -e "$(crontab_file)" ] || fail "卸载后应不剩区块"
}

register cron_symlinked_path_same_block
case_cron_symlinked_path_same_block() {
  new_project "$CASE_DIR/real/my-app"
  ln -s "$CASE_DIR/real" "$CASE_DIR/link"
  local via_link=$CASE_DIR/link/my-app/scripts/cron real
  real=$(phys "$CASE_DIR/real/my-app")
  try cron_sh "$via_link/install.sh"
  expect_rc 0 "经软链安装"
  expect_eq "$(block_owner MY_APP)" "$real" "区块记的是物理路径"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "经真实路径重装"
  expect_eq "$(block_count MY_APP)" 1 "同一个区块"
  try cron_sh "$via_link/uninstall.sh"
  expect_rc 0 "经软链卸载"
  [ ! -e "$(crontab_file)" ] || fail "卸载后应不剩区块"
}

register cron_symlinked_path_non_ascii_same_tag
case_cron_symlinked_path_non_ascii_same_tag() {
  # 标记取路径 cksum 的项目：经软链与真实路径算出的标记也一样
  new_project "$CASE_DIR/real/项目"
  ln -s "$CASE_DIR/real" "$CASE_DIR/link"
  expect_eq "$(dry_run_tag "$CASE_DIR/link/项目/scripts/cron/install.sh")" "$(dry_run_tag "$CRON/install.sh")" "经软链与真实路径的标记"
}

register cron_project_root_env_uninstall
case_cron_project_root_env_uninstall() {
  new_project "$CASE_DIR/app1"
  seed_crontab
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "以 app1 安装"
  local old
  old=$(phys "$CASE_DIR/app1")
  mv "$CASE_DIR/app1" "$CASE_DIR/app2"
  local cron=$CASE_DIR/app2/scripts/cron
  try cron_sh "$cron/uninstall.sh"
  expect_rc 0 "项目根改名后直接卸载"
  expect_out "无需卸载"
  expect_eq "$(block_count APP1)" 1 "新标记找不到旧区块"
  try cron_sh --env CRON_PROJECT_ROOT="$old" "$cron/uninstall.sh"
  expect_rc 0 "按旧项目根卸载"
  expect_out "已移除本项目的定时任务（crontab 标记 APP1）"
  expect_eq "$(crontab_text)" "$OTHER_JOBS" "旧区块已删，其它内容保留"
  try cron_sh "$cron/install.sh"
  expect_rc 0 "在新项目根重装"
  expect_eq "$(block_count APP1)/$(block_count APP2)" 0/1 "只剩新区块"
}

# ---------------------------------------------------------------------------
# tasks.conf

register cron_tasks_conf_boundary
case_cron_tasks_conf_boundary() {
  new_project "$CASE_DIR/my-app"
  local root
  root=$(phys "$CASE_DIR/my-app")
  # 界线行之前已启用的任务行（用户直接把示例改成了启用）与界线行之后的内容都要读到；注释与空行忽略。
  # 界线行之后整段换成下面这些（夹具追加的任务不要了）
  python3 - "$CRON/tasks.conf" <<'EOF'
import sys
from pathlib import Path
p = Path(sys.argv[1])
s = p.read_text(encoding="utf-8")
boundary = "# ---- 本项目的任务写在这一行之后 ----\n"
assert s.count(boundary) == 1, "tasks.conf 的界线行变了"
before, after = s.split(boundary)
before = before.replace("# 每日备份      | 0 3 * * *            | ./scripts/backup.sh --retention 7",
                        "每日备份      | 0 3 * * *            | ./scripts/backup.sh --retention 7")
assert "\n每日备份 " in before, "示例行变了"
after = "\n".join([
    "",
    "# 停用的任务 | * * * * * | echo disabled",
    "   ",
    "  高频巡检 | * * * * * +0,20 | node poll.js | tee -a out.log",
    "百分号 | @daily | date +%Y%m%d",
    "末行无换行 | 0 1 * * * | echo last",
])
p.write_text(before + boundary + after, encoding="utf-8")
EOF
  try cron_sh "$CRON/install.sh" --dry-run
  expect_rc 0 "dry-run"
  local body="cd \"$root\" && {"
  local log=">> \"$root/logs/cron/cron.log\" 2>&1"
  expect_out "# 每日备份"
  expect_out "0 3 * * * $body ./scripts/backup.sh --retention 7 ; } $log"
  expect_out "* * * * * $body node poll.js | tee -a out.log ; } $log"
  expect_out "* * * * * sleep 20 && $body node poll.js | tee -a out.log ; } $log"
  expect_out "@daily $body date +\\%Y\\%m\\%d ; } $log"
  expect_out "0 1 * * * $body echo last ; } $log"
  expect_not_out "echo disabled"
  expect_not_out "sleep 0"
  expect_not_out "同步数据"
  # 顺序：界线行之前的在前，之后的按原顺序
  local order
  order=$(printf '%s\n' "$OUT" | grep -E '^# (每日备份|高频巡检|百分号|末行无换行)$' | sed 's/^# //' | tr '\n' ' ')
  expect_eq "$order" "每日备份 高频巡检 百分号 末行无换行 " "任务顺序"
  try cron_sh "$CRON/install.sh"
  expect_rc 0 "安装"
  expect_out "  - 每日备份  (0 3 * * *)"
  expect_out "  - 高频巡检  (* * * * * +0,20)"
}

register cron_tasks_conf_errors
case_cron_tasks_conf_errors() {
  new_project "$CASE_DIR/my-app"
  cp "$CRON/tasks.conf" "$CASE_DIR/tasks.orig"
  { cat "$CASE_DIR/tasks.orig"; echo "缺命令 | 0 1 * * *"; } >"$CRON/tasks.conf"
  try cron_sh "$CRON/install.sh"
  expect_rc 1 "缺命令"
  expect_out "任务「缺命令」缺少命令"
  { cat "$CASE_DIR/tasks.orig"; echo "四个字段 | 0 1 * * | echo x"; } >"$CRON/tasks.conf"
  try cron_sh "$CRON/install.sh"
  expect_rc 1 "cron 表达式字段数不对"
  expect_out "任务「四个字段」的 cron 表达式不是 5 个字段"
  { cat "$CASE_DIR/tasks.orig"; echo "没有分隔符的一行"; } >"$CRON/tasks.conf"
  try cron_sh "$CRON/install.sh" --dry-run
  expect_rc 1 "没有分隔符"
  expect_out "缺少命令"
  [ ! -e "$(crontab_file)" ] || fail "清单有错时不应写出 crontab"
}

# 命令字段里的 % 都要转义（crontab 把未转义的 % 当作换行）：项目根、单独设置的 CRON_LOG_DIR、
# 带偏移的 sleep 行都算；区块里的注释行与 PATH= 行不是命令，原样保留。
has_line() { printf '%s\n' "$OUT" | grep -qxF -- "$1" || fail "${2:-输出}里应有整行：$1"; }
register cron_percent_escaped
case_cron_percent_escaped() {
  local root esc pbin logdir elog
  # 项目根含 %，PATH 也含 %（经软链指向自建 bin）
  ln -s "$BIN_CRON" "$CASE_DIR/b%in"
  new_project "$CASE_DIR/100%app"
  root=$(phys "$CASE_DIR/100%app")
  esc=${root//%/\\%}
  try cron_sh --env PATH="$CASE_DIR/b%in" "$CRON/install.sh" --dry-run
  expect_rc 0 "项目根含 % 时 dry-run"
  has_line "*/5 * * * * cd \"$esc\" && { echo hi ; } >> \"$esc/logs/cron/cron.log\" 2>&1" "项目根含 % 时"
  has_line "# $root" "注释行"
  has_line "PATH=$CASE_DIR/b%in" "PATH 行"
  expect_not_out "cd \"$root\""

  # 项目根不含 %，只有 CRON_LOG_DIR 含 %；带偏移的任务每条 sleep 行都要转义
  new_project "$CASE_DIR/plain-app"
  printf '%s\n' "偏移任务 | */5 * * * * +0,30 | echo off" >>"$CRON/tasks.conf"
  root=$(phys "$CASE_DIR/plain-app")
  logdir="$CASE_DIR/log%dir"
  elog=${logdir//%/\\%}/cron.log
  try cron_sh --env CRON_LOG_DIR="$logdir" "$CRON/install.sh" --dry-run
  expect_rc 0 "CRON_LOG_DIR 含 % 时 dry-run"
  has_line "*/5 * * * * cd \"$root\" && { echo hi ; } >> \"$elog\" 2>&1" "CRON_LOG_DIR 含 % 时"
  has_line "*/5 * * * * cd \"$root\" && { echo off ; } >> \"$elog\" 2>&1" "偏移 +0 那行"
  has_line "*/5 * * * * sleep 30 && cd \"$root\" && { echo off ; } >> \"$elog\" 2>&1" "偏移 sleep 那行"
  has_line "# $root" "注释行"
  expect_not_out "$logdir/cron.log"
}

# ---------------------------------------------------------------------------

set +e
run_cases "$@"
rc=$?
set -e

if compare_snapshots "$SNAP_BEFORE" "$(repo_snapshot)"; then
  echo "PASS repo_untouched"
else
  echo "FAIL repo_untouched: 真实仓库在运行前后不一致"
  rc=1
fi
exit "$rc"
