#!/bin/sh
#
# 把 tasks.conf 里的定时任务装进当前用户的 crontab。
#
# 只替换本项目的标记区块，crontab 里的其它内容原样保留；重复执行即为更新。
#
#   sh scripts/cron/install.sh             安装 / 更新
#   sh scripts/cron/install.sh --dry-run   只打印将要写入的区块，不动 crontab
#
set -eu

. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/common.sh"

DRY_RUN=0
case "${1:-}" in
  '') ;;
  --dry-run) DRY_RUN=1 ;;
  *) die "未知参数: $1（可用: --dry-run）" ;;
esac

LOG_FILE="$LOG_DIR/cron.log"

# 取第 $1 段；-s 让没有分隔符的行整段落空，好在后面报出明确的错
field() {
  trim "$(printf '%s\n' "$2" | cut -s -d'|' -f"$1")"
}

# 把一行任务展开成一条或多条 crontab 记录
emit_task() {
  _name=$1
  _schedule=$2
  _offsets=$3
  _cmd=$4

  # crontab 把未转义的 % 当作换行符，命令里的 % 必须转义
  _cmd=$(printf '%s' "$_cmd" | sed 's/%/\\%/g')
  # 命令整体套一层 { } 再重定向，否则命令里若有管道，日志只收得到最后一段的输出
  _body="cd \"$PROJECT_ROOT\" && { $_cmd ; } >> \"$LOG_FILE\" 2>&1"

  printf '# %s\n' "$_name"

  if [ -z "$_offsets" ]; then
    printf '%s %s\n' "$_schedule" "$_body"
    return
  fi

  for _off in $(printf '%s' "$_offsets" | tr ',' ' '); do
    case "$_off" in
      0) printf '%s %s\n' "$_schedule" "$_body" ;;
      *) printf '%s sleep %s && %s\n' "$_schedule" "$_off" "$_body" ;;
    esac
  done
}

generate_block() {
  printf '%s\n' "$MARKER_START"
  printf '# %s\n' "$PROJECT_ROOT"
  printf '# generated by install.sh at %s — 不要手改，改 tasks.conf 后重新安装\n' \
    "$(date '+%Y-%m-%d %H:%M:%S %z')"
  # cron 只给极小的 PATH，nvm / pyenv / homebrew 装的解释器都不在里面，
  # 这里把安装时的 PATH 固化进去。crontab 里的环境变量对其后的所有记录生效，
  # 所以本区块只能追加在末尾——下面写回 crontab 时保证了这一点。
  printf 'SHELL=/bin/sh\n'
  printf 'PATH=%s\n' "$PATH"

  while IFS= read -r _raw || [ -n "$_raw" ]; do
    case "$(trim "$_raw")" in
      ''|'#'*) continue ;;
    esac

    _name=$(field 1 "$_raw")
    _sched=$(field 2 "$_raw")
    _cmd=$(trim "$(printf '%s\n' "$_raw" | cut -s -d'|' -f3-)")

    [ -n "$_cmd" ] || die "任务「${_name}」缺少命令，检查 $TASKS_FILE"

    # cron 表达式末尾的 "+秒,秒" 是子分钟调度偏移
    _offsets=''
    case "$_sched" in
      *' +'*)
        _offsets=${_sched##* +}
        _sched=$(trim "${_sched% +*}")
        ;;
    esac

    case "$_sched" in
      @*) ;;
      *)
        [ "$(printf '%s\n' "$_sched" | wc -w | tr -d ' ')" = 5 ] \
          || die "任务「${_name}」的 cron 表达式不是 5 个字段: $_sched" ;;
    esac

    emit_task "$_name" "$_sched" "$_offsets" "$_cmd"
  done < "$TASKS_FILE"

  printf '%s\n' "$MARKER_END"
}

list_tasks() {
  while IFS= read -r _raw || [ -n "$_raw" ]; do
    case "$(trim "$_raw")" in
      ''|'#'*) continue ;;
    esac
    printf '  - %s  (%s)\n' "$(field 1 "$_raw")" "$(field 2 "$_raw")"
  done < "$TASKS_FILE"
}

require_crontab
[ -f "$TASKS_FILE" ] || die "找不到任务清单: $TASKS_FILE"

block=$(generate_block)

if [ "$DRY_RUN" -eq 1 ]; then
  printf '%s\n' "$block"
  exit 0
fi

mkdir -p "$LOG_DIR"

kept=$(read_crontab | strip_block)
if [ -n "$kept" ]; then
  write_crontab "$kept

$block"
else
  write_crontab "$block"
fi

printf '已安装定时任务（crontab 标记 %s）\n' "$CRON_TAG"
printf '  项目目录: %s\n' "$PROJECT_ROOT"
printf '  日志文件: %s\n' "$LOG_FILE"
list_tasks
printf '\n`crontab -l` 查看，`sh %s/uninstall.sh` 卸载\n' "$SCRIPT_DIR"

if [ "$(uname -s)" = Darwin ]; then
  printf '\nmacOS: 任务不执行时，到「系统设置 → 隐私与安全性 → 完全磁盘访问权限」为 /usr/sbin/cron 授权。\n'
fi
